sudo: false
addons:
  chrome: stable

language: ruby
rvm:
- 2.3.3
before_install:
  - rvm list
  - gem update
  - gem --version
script:
  - google-chrome-stable --version
  - chromedriver --version
  - bundle exec rspec
notifications:
  email:
    recipients:
    - mivanov1@gmail.com
    on_failure: change
    on_success: never
  slack:
    secure: BgRAqwHabAtIBgtApDjyUiND2SNxd4sHMgq4ffnJ+EoMme6RSUAeK0G6LLyaGAk6YcpCeWRGOccEpzai87R3ckv6uycUVGxFcTvPmCEClakbUelWovVEyVT3hPLWznxJ8pz3EVB2+5aJnAsTg5M2ZnYtk3a5C1mrPS+WKceE/Ls=
