sudo: false
addons:
  apt:
    packages:
      - google-chrome-stable
      - caca-utils
      - imagemagick

language: ruby
rvm:
- 2.4.1
script:
  - compare --version
  - bundle exec rspec spec/before_capture_spec.rb
notifications:
  email:
    recipients:
    - mivanov1@gmail.com
    on_failure: change
    on_success: never
  slack:
    secure: BgRAqwHabAtIBgtApDjyUiND2SNxd4sHMgq4ffnJ+EoMme6RSUAeK0G6LLyaGAk6YcpCeWRGOccEpzai87R3ckv6uycUVGxFcTvPmCEClakbUelWovVEyVT3hPLWznxJ8pz3EVB2+5aJnAsTg5M2ZnYtk3a5C1mrPS+WKceE/Ls=
